blank_issues_enabled: false
contact_links:
  - name: Frequently Asked Questions
    url: https://ferdium.org/faq
    about: The FAQ answers the most frequently asked questions on Easychat
  - name: "Bug or Recipe request: Main issue tracker"
    url: https://github.com/helloworld-88/easychat-app/issues
    about: Please log any bug report or recipe request in the `easychat-app` issue tracker, by selecting the category relevant to Recipes.
